# Generated by Django 3.1.3 on 2021-04-24 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=250)),
                ('playlist_description', models.TextField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('playlist_name', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='Songn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Rock', 'Rock'), ('HipHop', 'HipHop'), ('Jazz', 'Jazz'), ('Pop', 'Pop'), ('Blues', 'Blues'), ('Country', 'Country'), ('Heavy Metal', 'Heavy Metal'), ('Folk', 'Folk'), ('Classical', 'Classical'), ('Soul', 'Soul'), ('Electronic Dance Music', 'Electronic Dance Music'), ('Punk Rock', 'Punk Rock'), ('Reggae', 'Reggae'), ('House', 'House'), ('Funk', 'Funk'), ('Techno', 'Techno'), ('Alternative Rock', 'Alternative Rock'), ('Indie Rock', 'Indie Rock'), ('Trance', 'Trance'), ('Ambient', 'Ambient'), ('New Wave', 'New Wave'), ('Progressive Rock', 'Progressive Rock'), ('Dubset', 'Dubset'), ('Psychedelic Rock', 'Psychedelic Rock'), ('Opera', 'Opera'), ('Instrumental', 'Instrumental')], max_length=100)),
                ('album_art', models.ImageField(default='default-artwork.png', upload_to='album_art/')),
                ('audio_file', models.FileField(unique=True, upload_to='songs/')),
                ('released_year', models.IntegerField(blank=True, choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], null=True)),
                ('added_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('song_title', 'artist', 'album_title')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_dt', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist')),
                ('songn', models.ManyToManyField(to='music.Songn')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_dt', models.DateTimeField(auto_now_add=True)),
                ('songn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.songn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'songn')},
            },
        ),
    ]
