# Generated by Django 3.1.3 on 2021-04-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songn',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('HipHop', 'HipHop'), ('Jazz', 'Jazz'), ('Pop', 'Pop'), ('Blues', 'Blues'), ('Alternative', 'Alternative'), ('Country', 'Country'), ('Heavy Metal', 'Heavy Metal'), ('Folk', 'Folk'), ('Classical', 'Classical'), ('Soul', 'Soul'), ('Electronic Dance Music', 'Electronic Dance Music'), ('Punk Rock', 'Punk Rock'), ('Reggae', 'Reggae'), ('House', 'House'), ('Funk', 'Funk'), ('Techno', 'Techno'), ('Alternative Rock', 'Alternative Rock'), ('Indie Rock', 'Indie Rock'), ('Trance', 'Trance'), ('Ambient', 'Ambient'), ('New Wave', 'New Wave'), ('Progressive Rock', 'Progressive Rock'), ('Dubset', 'Dubset'), ('Psychedelic Rock', 'Psychedelic Rock'), ('Opera', 'Opera'), ('Instrumental', 'Instrumental')], max_length=100),
        ),
    ]
